export const earningsCompanies = [
  {
    name: "ASML", ticker: "ASML", flag: "🇳🇱", date: "07-15", status: "已发", phase: "上游先行", layer: "设备",
    fiscal: "CY26 Q2", revenue: "€9.3bn（高于公司指引上限）", eps: "€7.59", currency: "EUR", grade: "A",
    focus: "订单、EUV/High-NA、装机管理业务与地区结构",
    highlights: "收入和全年指引上修，但超预期贡献更多来自装机管理业务，因此需要把服务升级收入与设备台数分开判断。",
    guidance: "重点核对全年销售额、毛利率、EUV 系统交付与中国区收入口径。",
    external: "市场关注上修能否由设备台数和客户资本开支持续支撑。",
    analysis: "对半导体设备链的意义大于单季 EPS：量、价、服务收入的驱动不同。",
    source: "https://www.asml.com/en/investors/financial-results",
  },
  {
    name: "台积电", ticker: "TSM", flag: "🇹🇼", date: "07-16", status: "已发", phase: "上游先行", layer: "晶圆代工",
    fiscal: "CY26 Q2", revenue: "US$40.2bn（公司指引上沿）", eps: "ADR $4.31", currency: "USD", grade: "A",
    focus: "先进节点、CoWoS、AI 加速器需求与资本开支",
    highlights: "营收达到指引上沿、毛利率强于指引；净利包含一次性股权处置影响，经营表现与一次性收益应分拆。",
    guidance: "重点跟踪下一季收入、毛利率、2nm 爬坡与年度资本开支。",
    external: "设备与先进封装链更关注资本开支上修，而不是一次性利润。",
    analysis: "先进节点和 AI HPC 仍是主线，但海外厂与新节点折旧会影响后续毛利率。",
    source: "https://investor.tsmc.com/english/quarterly-results/2026/q2",
  },
  {
    name: "谷歌", ticker: "GOOGL", flag: "🇺🇸", date: "07-22", status: "已发", phase: "大盘密集周", layer: "云与平台",
    fiscal: "CY26 Q2", revenue: "$119.8bn", eps: "GAAP $9.11（含投资收益）", currency: "USD", grade: "A",
    focus: "Cloud 增速、订单储备、AI 资本开支与自由现金流",
    highlights: "Cloud 收入继续加速；GAAP EPS 受权益投资浮盈影响，分析经营趋势时应优先看经营利润与现金流。",
    guidance: "重点跟踪年度资本开支、Cloud 产能供给和 AI 产品变现。",
    external: "市场在高增速与自由现金流承压之间重新定价。",
    analysis: "对光通信和服务器链的关键变量是 capex 与网络端口扩张，而非单季会计利润。",
    source: "https://abc.xyz/investor/",
  },
  {
    name: "特斯拉", ticker: "TSLA", flag: "🇺🇸", date: "07-22", status: "已发", phase: "大盘密集周", layer: "终端/AI",
    fiscal: "CY26 Q2", revenue: "$28.24bn", eps: "调整后 $0.33", currency: "USD", grade: "A",
    focus: "汽车现金流能否支撑 AI、自动驾驶和机器人资本开支",
    highlights: "营收与交付强，但利润率和自由现金流承压，收入增长与盈利质量出现分化。",
    guidance: "关注全年资本开支、Robotaxi、Optimus 与汽车毛利率。",
    external: "市场更关注现金流和执行，而不是单纯交付数量。",
    analysis: "AI 投入能否由核心汽车业务持续供养，是估值框架的关键。",
    source: "https://ir.tesla.com/",
  },
  {
    name: "SAP", ticker: "SAP", flag: "🇩🇪", date: "07-23", status: "已发", phase: "大盘密集周", layer: "企业软件",
    fiscal: "CY26 Q2", revenue: "€9.9bn", eps: "ADR $1.85", currency: "EUR", grade: "A",
    focus: "云订单、AI 应用、并购与利润率",
    highlights: "云订单增速改善，但并购投入稀释利润指引。",
    guidance: "观察云收入、当前云订单和并购后的利润贡献。",
    external: "市场需要区分主动买增长和经营恶化。",
    analysis: "订单领先指标改善，但 AI 变现仍需落到续费和客单价。",
    source: "https://www.sap.com/investors/en.html",
  },
  {
    name: "联发科", ticker: "2454", flag: "🇹🇼", date: "待确认", status: "待确认", phase: "大盘密集周", layer: "芯片设计",
    fiscal: "CY26 Q2", revenue: "NT$152.2bn（自结）", eps: "待正式法说会", currency: "TWD", grade: "C",
    focus: "旗舰手机、边缘 AI 与定制 ASIC 项目",
    highlights: "季度营收已披露，但法说会日期和完整利润数据需等待官方确认。",
    guidance: "关注 ASIC 项目放量、2nm 手机芯片和毛利率。",
    external: "第三方日期未获 IR 页面确认，不作为正式日历口径。",
    analysis: "边缘 AI 与云 ASIC 是中期增量，手机周期仍决定短期利润。",
    source: "https://corp.mediatek.com/investor-relations",
  },
  {
    name: "微软", ticker: "MSFT", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "大盘密集周", layer: "云与平台",
    fiscal: "FY26 Q4", revenue: "一致预期约 $87.6bn", eps: "一致预期约 $4.21", currency: "USD", grade: "B",
    focus: "Azure 增速、AI 产能约束、capex、Copilot 席位与 ARPU",
    highlights: "本季核心问题是 Azure 的 AI 贡献是否继续提高，以及新增算力能否缓解供给约束。",
    guidance: "重点看 FY27 收入、利润率、资本开支与折旧指引。",
    external: "市场预期高，任何 capex 与变现节奏错配都会放大波动。",
    analysis: "对光模块链最重要的是网络资本开支和集群拓扑，而非 Copilot 单一指标。",
    source: "https://www.microsoft.com/en-us/Investor",
  },
  {
    name: "Meta", ticker: "META", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "大盘密集周", layer: "云与平台",
    fiscal: "CY26 Q2", revenue: "一致预期约 $60.2bn", eps: "一致预期约 $7.17", currency: "USD", grade: "B",
    focus: "广告 AI 变现、capex、开源模型与 Reality Labs",
    highlights: "收入高增长与 AI 重投入并行，需观察利润率能否承受资本开支和运营费用上修。",
    guidance: "关注全年 capex、费用、广告转化效率和基础设施周期。",
    external: "市场争议集中在 AI 投入回报周期。",
    analysis: "其自建集群对交换、光互连和定制 ASIC 的映射价值很高。",
    source: "https://investor.atmeta.com/",
  },
  {
    name: "Arm", ticker: "ARM", flag: "🇬🇧", date: "07-29", status: "待公布", phase: "大盘密集周", layer: "芯片 IP",
    fiscal: "FY27 Q1", revenue: "一致预期约 $1.26bn", eps: "一致预期约 $0.40", currency: "USD", grade: "B",
    focus: "版税、CSS、Neoverse 与数据中心渗透",
    highlights: "版税增长与授权波动需要分开，数据中心 CPU 是 AI 关联度最高的增量。",
    guidance: "观察下一季授权、版税和服务器份额。",
    external: "市场关注高估值能否由持续版税增长消化。",
    analysis: "对 AI 基础设施的影响更多来自 CPU 架构和整机设计，不直接等同 GPU 周期。",
    source: "https://investors.arm.com/",
  },
  {
    name: "SK海力士", ticker: "000660", flag: "🇰🇷", date: "07-29", status: "待公布", phase: "大盘密集周", layer: "存储/HBM",
    fiscal: "CY26 Q2", revenue: "一致预期约 ₩83万亿", eps: "关注营业利润约 ₩65万亿", currency: "KRW", grade: "B",
    focus: "HBM3E/HBM4 出货、ASP、长协与 TSV 良率",
    highlights: "HBM 是 AI 内存最直接的先行指标，需把创纪录利润与市场高预期同时纳入。",
    guidance: "关注 HBM4 认证、2027 长协、传统 DRAM/NAND 定价和资本开支。",
    external: "财报数字强但若低于高预期，股价仍可能负反馈。",
    analysis: "存储周期需要同时验证价格、位元增长和资本纪律。",
    source: "https://news.skhynix.com/category/ir/",
  },
  {
    name: "苹果", ticker: "AAPL", flag: "🇺🇸", date: "07-30", status: "待公布", phase: "大盘密集周", layer: "终端",
    fiscal: "FY26 Q3", revenue: "一致预期约 $108.9bn", eps: "一致预期约 $1.88", currency: "USD", grade: "B",
    focus: "iPhone、大中华区、服务收入与 Apple Intelligence",
    highlights: "服务业务决定利润质量，AI 功能落地节奏影响换机预期。",
    guidance: "关注毛利率、供应链成本、服务增速和新品周期。",
    external: "市场担心 AI 产品节奏慢于竞争对手。",
    analysis: "对半导体链的 read-through 是手机需求、存储价格和先进制程利用率。",
    source: "https://investor.apple.com/",
  },
  {
    name: "亚马逊", ticker: "AMZN", flag: "🇺🇸", date: "07-30", status: "待公布", phase: "大盘密集周", layer: "云与平台",
    fiscal: "CY26 Q2", revenue: "一致预期约 $196.2bn", eps: "一致预期约 $1.82", currency: "USD", grade: "B",
    focus: "AWS 增速、订单储备、Trainium、capex 与自由现金流",
    highlights: "AWS 增速与 AI 产能供给是主线，资本开支与现金流之间的张力需要同步观察。",
    guidance: "关注 AWS 增速、AI 芯片部署、网络资本开支和营业利润。",
    external: "市场关注自研芯片能否改善单位算力经济性。",
    analysis: "其网络与定制 ASIC 投入直接映射光模块、交换和服务器供应链。",
    source: "https://ir.aboutamazon.com/",
  },
  {
    name: "三星电子", ticker: "005930", flag: "🇰🇷", date: "07-30", status: "初值已发", phase: "大盘密集周", layer: "存储/HBM",
    fiscal: "CY26 Q2", revenue: "初值约 ₩171万亿", eps: "营业利润初值约 ₩89.4万亿", currency: "KRW", grade: "A",
    focus: "HBM 认证、DRAM/NAND 价格、代工与系统 LSI",
    highlights: "初步业绩显示存储盈利显著改善，完整报告仍需看分部结构和 HBM 认证。",
    guidance: "关注 HBM4、传统内存合约价和资本开支。",
    external: "传统 DRAM 与 HBM 定价机制不同，盈利比较不可简单外推。",
    analysis: "完整分部数据是判断内存超级周期质量的关键。",
    source: "https://www.samsung.com/global/ir/",
  },
  {
    name: "东京电子", ticker: "8035", flag: "🇯🇵", date: "07-30", status: "待公布", phase: "半导体与设备", layer: "设备",
    fiscal: "FY27 Q1", revenue: "一致预期约 ¥761.7bn", eps: "聚合预期约 ¥357.66", currency: "JPY", grade: "B",
    focus: "WFE、AI 存储与中国区收入",
    highlights: "AI 相关存储和先进逻辑支持设备需求，但出口限制和中国敞口需要单列。",
    guidance: "关注半年度指引、订单和客户结构。",
    external: "单季预测可能由半年度口径倒推，需标明差异。",
    analysis: "设备公司需要从订单、验收和收入确认三个时点观察。",
    source: "https://www.tel.com/ir/",
  },
  {
    name: "铠侠", ticker: "285A", flag: "🇯🇵", date: "07-31", status: "待公布", phase: "半导体与设备", layer: "NAND",
    fiscal: "FY27 Q1", revenue: "公司指引约 ¥1.75万亿", eps: "关注营业利润约 ¥1.30万亿", currency: "JPY", grade: "A",
    focus: "NAND ASP、企业级 SSD 与位元出货",
    highlights: "作为 NAND 纯玩家，其价格和利润率是存储周期的重要验证。",
    guidance: "关注价格、出货量、库存和资本纪律。",
    external: "低基数会放大同比增幅，应结合环比判断。",
    analysis: "企业级 SSD 的 AI 需求能否抵消消费端波动是核心。",
    source: "https://www.kioxia-holdings.com/en-jp/ir.html",
  },
  {
    name: "AMD", ticker: "AMD", flag: "🇺🇸", date: "08-04", status: "待公布", phase: "半导体与设备", layer: "GPU/CPU",
    fiscal: "CY26 Q2", revenue: "一致预期约 $11.3bn", eps: "一致预期约 $1.60", currency: "USD", grade: "B",
    focus: "MI350/MI400、EPYC、AI GPU 指引与客户",
    highlights: "数据中心 GPU 和 CPU 份额是增长核心，低基数会放大 EPS 同比。",
    guidance: "关注 AI GPU 收入、机架系统、客户扩张和毛利率。",
    external: "市场需要验证大型客户设计导入能否转为规模收入。",
    analysis: "二供逻辑只有在系统交付、软件生态和客户收入同时兑现时成立。",
    source: "https://ir.amd.com/",
  },
  {
    name: "英伟达", ticker: "NVDA", flag: "🇺🇸", date: "08-26", status: "待公布", phase: "半导体与设备", layer: "GPU/系统",
    fiscal: "FY27 Q2", revenue: "一致预期约 $91.7bn", eps: "一致预期约 $2.08", currency: "USD", grade: "B",
    focus: "平台交付、Rubin 过渡、网络业务、HBM 与 CoWoS",
    highlights: "公司指引本身已隐含高增长，关键在下一季平台切换、毛利率和供应约束。",
    guidance: "关注 Rubin、网络收入、中国政策和供应链。",
    external: "高预期环境下，超预期幅度比绝对增长更重要。",
    analysis: "光通信需跟踪每机架网络带宽与端口密度，而不只看 GPU 数量。",
    source: "https://investor.nvidia.com/",
  },
  {
    name: "迈威尔", ticker: "MRVL", flag: "🇺🇸", date: "约08-27", status: "待确认", phase: "半导体与设备", layer: "定制芯片/互连",
    fiscal: "FY27 Q2", revenue: "公司指引约 $2.7bn", eps: "一致预期约 $0.93", currency: "USD", grade: "B",
    focus: "定制 ASIC、1.6T DSP、电互连与硅光",
    highlights: "定制 XPU 和光电互连是两条增长线，需确认客户集中与项目节奏。",
    guidance: "关注下一季 AI 收入、DSP 与 ASIC 设计导入。",
    external: "其竞争位置需要与 Broadcom 的客户和项目份额对比。",
    analysis: "光通信相关收入是 1.6T 放量的重要侧面验证。",
    source: "https://investor.marvell.com/",
  },
  {
    name: "博通", ticker: "AVGO", flag: "🇺🇸", date: "09-03", status: "待公布", phase: "收尾", layer: "ASIC/交换/CPO",
    fiscal: "FY26 Q3", revenue: "一致预期约 $29.2bn", eps: "一致预期约 $3.22", currency: "USD", grade: "B",
    focus: "定制 ASIC、交换平台、AI 半导体收入与 CPO",
    highlights: "AI 半导体收入和客户扩展是核心，VMware 利润与芯片增长需要分拆。",
    guidance: "关注 AI 收入、客户数、102.4T 交换平台和 CPO 导入。",
    external: "市场对新增客户和长期订单能见度预期较高。",
    analysis: "它是 CPO、交换芯片与定制 XPU 三条线最直接的交汇点。",
    source: "https://investors.broadcom.com/",
  },
  {
    name: "甲骨文", ticker: "ORCL", flag: "🇺🇸", date: "约09-09", status: "待确认", phase: "收尾", layer: "云基础设施",
    fiscal: "FY27 Q1", revenue: "一致预期约 $19.1bn", eps: "一致预期约 $1.72", currency: "USD", grade: "B",
    focus: "OCI 增速、RPO、数据中心建设与资本开支",
    highlights: "订单储备提供需求能见度，但建设节奏和融资成本决定收入确认。",
    guidance: "关注 OCI、RPO、capex、毛利率和交付能力。",
    external: "市场争议是巨额订单能否按期转成可盈利收入。",
    analysis: "对光模块与电力链的映射取决于实际园区投产而非合同金额。",
    source: "https://investor.oracle.com/",
  },
  {
    name: "美光", ticker: "MU", flag: "🇺🇸", date: "约09-29", status: "待确认", phase: "收尾", layer: "存储/HBM",
    fiscal: "FY26 Q4", revenue: "公司指引约 $50bn", eps: "公司指引约 $31", currency: "USD", grade: "A",
    focus: "HBM3E/HBM4、DRAM/NAND 价格、毛利率与产能",
    highlights: "极高利润率和收入指引反映存储周期强度，但也提高了后续预期门槛。",
    guidance: "关注 HBM 供需、2027 长协、传统内存价格和资本开支。",
    external: "市场需要判断极端利润率的可持续性。",
    analysis: "HBM 排产与传统内存涨价共同决定设备、材料和封装链斜率。",
    source: "https://investors.micron.com/",
  },
  {
    name: "英特尔", ticker: "INTC", flag: "🇺🇸", date: "07-23", status: "已发", phase: "配套标的", layer: "逻辑/代工",
    fiscal: "CY26 Q2", revenue: "$16.13bn", eps: "Non-GAAP $0.42", currency: "USD", grade: "A",
    focus: "数据中心、代工外部收入、18A 与资本开支",
    highlights: "收入和数据中心业务改善；GAAP EPS 受非经营性、非现金项目影响，需与经营表现分开。",
    guidance: "关注下一季收入、毛利率、代工客户和资本开支。",
    external: "外部代工收入改善是重要但仍处早期的信号。",
    analysis: "真正拐点需要外部客户、良率和现金流同时改善。",
    source: "https://www.intc.com/",
  },
  {
    name: "高通", ticker: "QCOM", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "配套标的", layer: "端侧/CPU",
    fiscal: "FY26 Q3", revenue: "一致预期约 $9.67bn", eps: "一致预期约 $2.21", currency: "USD", grade: "B",
    focus: "Snapdragon、汽车、数据中心 CPU 与苹果基带流失",
    highlights: "端侧 AI 与汽车增长需要对冲手机和大客户流失。",
    guidance: "关注手机需求、汽车订单和数据中心计划。",
    external: "客户集中下降是中期估值变量。",
    analysis: "数据中心 CPU 若形成产品收入，才会进入 AI 基建映射。",
    source: "https://investor.qualcomm.com/",
  },
  {
    name: "德州仪器", ticker: "TXN", flag: "🇺🇸", date: "07-22", status: "已发", phase: "配套标的", layer: "模拟芯片",
    fiscal: "CY26 Q2", revenue: "$5.463bn", eps: "GAAP $2.14", currency: "USD", grade: "A",
    focus: "库存、汽车/工业需求、毛利率与资本开支",
    highlights: "收入和 EPS 高于预期，库存天数继续下降，但市场更关注后续指引斜率。",
    guidance: "关注下一季收入、库存、汽车和工业需求。",
    external: "业绩好不等于股价上涨，预期位置同样重要。",
    analysis: "模拟芯片是广谱周期验证，不应简单等同 AI 需求。",
    source: "https://investor.ti.com/",
  },
  {
    name: "泛林集团", ticker: "LRCX", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "配套标的", layer: "设备",
    fiscal: "FY26 Q4", revenue: "一致预期约 $6.65bn", eps: "一致预期约 $1.68", currency: "USD", grade: "B",
    focus: "刻蚀/沉积、HBM、3D NAND 与先进逻辑 WFE",
    highlights: "存储设备复苏和先进逻辑支撑收入，需核验全年 WFE 与中国敞口。",
    guidance: "关注订单、存储占比、毛利率和出口限制。",
    external: "WFE 预测与公司订单可能存在时滞。",
    analysis: "HBM 资本开支对其刻蚀和沉积环节传导较直接。",
    source: "https://investor.lamresearch.com/",
  },
  {
    name: "Cadence", ticker: "CDNS", flag: "🇺🇸", date: "待确认", status: "待确认", phase: "配套标的", layer: "EDA",
    fiscal: "CY26 Q2", revenue: "一致预期约 $1.58bn", eps: "一致预期约 $2.05", currency: "USD", grade: "B",
    focus: "EDA 订单、backlog、AI 芯片设计与系统分析",
    highlights: "EDA 是 AI 芯片设计的卖铲子环节，订单和 backlog 比单季收入更重要。",
    guidance: "关注全年收入、利润率和订单储备。",
    external: "高估值依赖长期双位数增长。",
    analysis: "系统级设计复杂度提升是结构性驱动。",
    source: "https://investor.cadence.com/",
  },
  {
    name: "Amkor", ticker: "AMKR", flag: "🇺🇸", date: "待确认", status: "待确认", phase: "配套标的", layer: "封测",
    fiscal: "CY26 Q2", revenue: "一致预期约 $1.81bn", eps: "一致预期约 $0.47", currency: "USD", grade: "B",
    focus: "先进封装、HDFO、美国新厂与客户",
    highlights: "先进封装是 AI 芯片的关键瓶颈，需验证新产能利用率和客户导入。",
    guidance: "关注先进封装收入、资本开支和毛利率。",
    external: "扩产初期折旧可能先于收入。",
    analysis: "封装价值量提升成立，但利润兑现取决于良率与利用率。",
    source: "https://ir.amkor.com/",
  },
  {
    name: "信越化学", ticker: "4063", flag: "🇯🇵", date: "07-24", status: "已发", phase: "配套标的", layer: "材料",
    fiscal: "FY27 Q1", revenue: "¥662.4bn", eps: "¥70.24", currency: "JPY", grade: "A",
    focus: "硅晶圆、光刻胶、利润率与全年指引",
    highlights: "利润增长质量优于收入，但不同第三方共识口径可能导致 beat/miss 判断反转。",
    guidance: "关注全年收入、利润和半导体材料分部。",
    external: "实际值应优先于不一致的第三方共识。",
    analysis: "材料链表现更偏稳健，不应与设备高弹性混为一谈。",
    source: "https://www.shinetsu.co.jp/en/ir/",
  },
  {
    name: "安费诺", ticker: "APH", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "配套标的", layer: "高速互连",
    fiscal: "CY26 Q2", revenue: "一致预期约 $8.18bn", eps: "一致预期约 $1.16", currency: "USD", grade: "B",
    focus: "高速连接器、铜互连、电源连接和 AI 数据中心",
    highlights: "订单和 IT datacom 增速是 AI 互连需求的先行验证。",
    guidance: "关注订单、并购整合、利润率和数据中心占比。",
    external: "连接器需求可验证铜与光并行演进。",
    analysis: "高速互连价值量应按机架和端口密度衡量。",
    source: "https://investors.amphenol.com/",
  },
  {
    name: "康宁", ticker: "GLW", flag: "🇺🇸", date: "待确认", status: "待确认", phase: "配套标的", layer: "光纤/光通信",
    fiscal: "CY26 Q2", revenue: "一致预期约 $4.62bn", eps: "一致预期约 $0.76", currency: "USD", grade: "B",
    focus: "企业网络、数据中心光纤、订单与产能",
    highlights: "AI 数据中心推动高密度光连接，分部增速和订单比集团收入更有解释力。",
    guidance: "关注光通信分部、客户协议和产能。",
    external: "指引与高预期的差异可能放大股价波动。",
    analysis: "它是验证光纤与连接基础设施需求的重要海外读数。",
    source: "https://investor.corning.com/",
  },
  {
    name: "西部数据", ticker: "WDC", flag: "🇺🇸", date: "07-29", status: "待公布", phase: "配套标的", layer: "HDD",
    fiscal: "FY26 Q4", revenue: "一致预期约 $3.69bn", eps: "一致预期约 $3.29", currency: "USD", grade: "B",
    focus: "近线大容量 HDD、云厂需求、容量出货和价格",
    highlights: "分拆后业务更纯，AI 数据存储需求可从容量位元和价格验证。",
    guidance: "关注云客户、价格、产能和毛利率。",
    external: "HDD 与 NAND 是不同存储层级，不能混合判断。",
    analysis: "AI 数据量增长可能同时利好近线 HDD 与企业级 SSD。",
    source: "https://investor.wdc.com/",
  },
  {
    name: "Celestica", ticker: "CLS", flag: "🇨🇦", date: "待确认", status: "待确认", phase: "配套标的", layer: "服务器/交换机代工",
    fiscal: "CY26 Q2", revenue: "一致预期约 $4.24bn", eps: "一致预期约 $2.28", currency: "USD", grade: "B",
    focus: "AI 服务器、白盒交换机、客户与产能",
    highlights: "其硬件平台业务直接承接云厂 capex，订单与产能利用率是关键。",
    guidance: "关注全年收入、客户集中和利润率。",
    external: "高增速同时伴随高客户集中风险。",
    analysis: "对 800G/1.6T 交换需求有较强 read-through。",
    source: "https://corporate.celestica.com/investor-relations",
  },
  {
    name: "GE Vernova", ticker: "GEV", flag: "🇺🇸", date: "07-22", status: "已发", phase: "配套标的", layer: "电力",
    fiscal: "CY26 Q2", revenue: "$11.10bn", eps: "调整后 $2.47", currency: "USD", grade: "A",
    focus: "订单、在手订单、数据中心电气化与自由现金流",
    highlights: "收入和订单强，但调整后 EPS 低于预期；订单簿与利润表给出不同信号。",
    guidance: "关注全年收入、自由现金流、电气化和风电。",
    external: "数据中心订单增长需要结合交付周期。",
    analysis: "电力基础设施是 AI capex 的约束环节，订单先于收入兑现。",
    source: "https://www.gevernova.com/investors",
  },
  {
    name: "ServiceNow", ticker: "NOW", flag: "🇺🇸", date: "07-22", status: "已发", phase: "配套标的", layer: "软件",
    fiscal: "CY26 Q2", revenue: "$3.987bn", eps: "调整后 $0.90", currency: "USD", grade: "A",
    focus: "AI ACV、订阅收入、cRPO 与毛利率",
    highlights: "AI 合同增长和订单领先指标强，但云与 AI 使用增加压低订阅毛利率。",
    guidance: "关注订阅收入、cRPO、AI ACV 和毛利率。",
    external: "AI 变现可能先表现为收入与成本同时上升。",
    analysis: "软件 AI 商业化需要同时看合同、使用量、毛利和续费。",
    source: "https://www.servicenow.com/company/investor-relations.html",
  },
  {
    name: "IBM", ticker: "IBM", flag: "🇺🇸", date: "07-22", status: "已发", phase: "配套标的", layer: "软件/基础设施",
    fiscal: "CY26 Q2", revenue: "$17.16bn", eps: "调整后 $2.93", currency: "USD", grade: "A",
    focus: "软件、大机、咨询、自由现金流与全年指引",
    highlights: "大机收入下滑拖累增长，软件增速也需要结合上季基数判断。",
    guidance: "关注全年收入、软件增速、自由现金流和基础设施。",
    external: "AI 预算可能挤压部分传统 IT 升级。",
    analysis: "这是观察 AI capex 对传统企业 IT 二阶影响的样本。",
    source: "https://www.ibm.com/investor",
  },
];

export const earningsPhases = [
  { id: "上游先行", label: "上游先行读数", note: "7 月中 · 设备 + 代工" },
  { id: "大盘密集周", label: "大盘股密集周", note: "7 月下旬 · 云厂 + 内存" },
  { id: "半导体与设备", label: "半导体与设备", note: "7 月底–8 月 · GPU + WFE + NAND" },
  { id: "收尾", label: "收尾", note: "9 月 · ASIC + 云 + 存储" },
  { id: "配套标的", label: "AI 产业链配套标的", note: "互连 · 封测 · 材料 · 电力 · 软件" },
];
